---
title: "VIOLENCIA SEXUAL - COLOMBIA"
output: 
  flexdashboard::flex_dashboard:
    logo: "img/logo.png"
    theme:
      bg: "#E1E8Ec"
      fg: "#0B3948" 
      primary: "#416165"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# paquetes empleados
library(flexdashboard)

library(readr)

library(tidyr)

library(sf)
library(rnaturalearth)
library(ggplot2)
library(gridExtra)
library(raster)
library(scales)

# carga de mapas
COL <- read_sf("map/COL_adm0.shp")
COLdep <- read_sf("map/COL_adm1.shp")
COLmun <- read_sf("map/COL_adm2.shp")

# bases de datos
dptos <- read_csv("data/dptos.csv")
casosCo <- read_csv("data/casosCo.csv")
sex22 <- read_csv("data/sex22.csv")

```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Casos 2021

```{r}
library(ggplot2)

# Ordenar los datos por casosh de mayor a menor
casosCo <- casosCo[order(-casosCo$casos), ]

# Crear una paleta de colores degradada de rojos
red_palette <- colorRampPalette(c("#FFC685", "#AE123A"))(nrow(casosCo))

# Gráfico de barras
ggplot(casosCo, aes(x = reorder(ndep, casos), y = casosh, fill = casos)) + 
  geom_col() + 
  geom_text(aes(label = casos), hjust = -0.1, size = 2, color = "gray30") +
  scale_y_continuous(labels = scales::comma, name = "", expand = expansion(mult = c(0, 0.05))) +
  scale_fill_gradientn(colors = red_palette, guide = FALSE) +
  coord_flip() + 
  theme_minimal() +
  theme(
    text = element_text(color = "gray30"),
    axis.text.y = element_text(size = 5, color = "gray30"),
    axis.text.x = element_text(size = 5, color = "gray30"),
    legend.position = "none",
    plot.margin = margin(1, 1, 1, 2),
    axis.title = element_text(size = 6)
  ) +
  labs(
    x = "Departamentos",
    y = "Casos "
  )

```

### Antioquia

```{r}
ant<- COLmun %>% 
        dplyr::filter(NAME_1 == "Antioquia")

ggplot() +
  geom_sf(data=ant, aes(fill = ID_2), color = "black", size = 0.25) +
  theme(aspect.ratio=1, axis.text.x = element_blank(), axis.text.y = element_blank())+
  scale_fill_distiller(name="Casos", palette = "YlOrRd", breaks = scales::pretty_breaks(n = 5))+
  labs(title=" ", x = " ", y = " ")


```


### Cundinamarca

```{r}
cun<- COLmun %>% 
        dplyr::filter(NAME_1 == "Cundinamarca")

ggplot() +
  geom_sf(data=cun, aes(fill = ID_2), color = "black", size = 0.25) +
  theme(aspect.ratio=1, axis.text.x = element_blank(), axis.text.y = element_blank())+
  scale_fill_distiller(name="Casos", palette = "YlOrRd", breaks = scales::pretty_breaks(n = 5))+
  labs(title=" ", x = " ", y = " ")

```


### Valle del Cauca

```{r}
val<- COLmun %>% 
        dplyr::filter(NAME_1 == "Valle del Cauca")

ggplot() +
  geom_sf(data=val, aes(fill = ID_2), color = "black", size = 0.25) +
  theme(aspect.ratio=1, axis.text.x = element_blank(), axis.text.y = element_blank())+
  scale_fill_distiller(name="Casos", palette = "YlOrRd", breaks = scales::pretty_breaks(n = 5))+
  labs(title=" ", x = " ", y = " ")+
  coord_sf(xlim = c(-77.8, -75.6), ylim = c(3, 5))

```



Column {data-width=350}
-----------------------------------------------------------------------

### Mapa 

```{r}
require(sp)
 require(rgdal)
 require(raster)
 require(RColorBrewer)
library(tidyverse)

 mi.palette <- brewer.pal(n = 7, name = "OrRd")   # paleta de colores
 mapco=shapefile("map/depto.shp")  # importa mapa en formato .shp
 # colombia=readRDS("data/Colombia.RDS")
 # colombia$departamento_nom= str_to_upper(colombia$departamento_nom)
 # t=table(colombia$departamento_nom,colombia$estado)
 fallecidos=c(15174,3876,26516,807,2417,2151,880,1333,2388,3487,6495,382,2880,
             1296,1380,2076,2861,3961,1635,2119,6934,1546,3411,11929,400,844,
             620,249,29,87,17,45,133) # vector con información
 mapco@data$fallecidos=fallecidos # se adiciona variable con 33 valores = 33 dptos, en mismo orden
 spplot(mapco[,6], col.regions = mi.palette, cuts = 6)  # mapa
```


### Indicadores 2022

Column {data-width=50}
-----------------------------------------------------------------------

### Casos 2022

```{r}
casos = sum(casosCo$casos)
valueBox(casos, icon = "fa-pencil")
```

### Casos mujeres 2022

```{r}
casosm = sum(casosCo$casosm)
valueBox(casosm, icon = "fa-comments")
```

### Casos hombres 2022

```{r}
casosh = sum(casosCo$casosh)
valueBox(casosh, icon = "fa-trash" )
```

### Contact Rate

```{r}
gauge(90, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Average Rating 

```{r}
gauge(37.4, min = 0, max = 50, gaugeSectors(
  success = c(41, 50), warning = c(21, 40), danger = c(0, 20)
))
```

### Cancellations

```{r}
gauge(7, min = 0, max = 10, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

